spring:
  application:
    name: service-review
  config:
    import: nacos:service-review.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1
      config:
        server-addr: localhost:8848
        file-extension: yaml

server:
  port: 8085