spring:
  application:
    name: service-ai
  config:
    import: optional:nacos:service-ai.yaml   # ? Nacos ???
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

server:
  port: 8085