spring:
  application:
    name: service-user
  config:
    import: nacos:service-user.yaml   # ? Nacos ???
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: 127.0.0.1
      config:
        server-addr: localhost:8848
        file-extension: yaml

server:
  port: 8081   # ??????????????????